kleros/court

src/components/notification-settings.js
Issue: In new accounts the notification keys do not exist causing the page to crash when it tries to load the notification settings for the account.
- Add defaults for notification setting keys that do not exist
=> fix(notification-settings): add defaults for new accounts

package.json, yarn.lock
- This version of Archon is compatible with the Realitio scripts that are currently deployed
=> chore: archon v0.9.0

src/components/case-details-card.js
History does not work with `complexRulings`. Hide it if not `single-select` until they have been implemented.
=> refactor(case-details-card): hide history if not single-select

src/components/evidence-card.js
=> fix: show correct evidence links

src/components/case-details-card.js
allows for the use of parameter `evidenceDisplayHeight` in meta evidence to change the rendered height of the evidence display iFrame
=> refactor(cases): optional height for evidence display

src/bootstrap/dataloader.js
There is an issue with the meta evidence display used in case 544, but no evidence tampering. This hot fix will let jurors adjudicate the case.
=> hotfix: work around failed prevalidation

src/bootstrap/drizzle.js
Drizzle options are problematic. When you add a contract for a network but you don't add contracts for all networks, Drizzle breaks UI. This currently breaks some functionality on Ropsten, because there is no MerkleRedeem contract for Ropsten. Removing this configuration altogether fixes this issue.
Also, this configuration is not used at all, claim logic does not use Drizzle.
=> fix(drizzle): remove MerkleReedem options from drizzle options

src/components/claim-modal.js
Bug: Transaction payload does not filter out already claimed `weeks`. This causes the claim transaction to revert if you already claimed the past period.
How to Reproduce: Try to claim your reward and see that tx is reverting if you have claimed in a past period at least once.
How to Verify This Fix: Try to claim your reward on deploy preview. The transaction should be successful and you should see the amount you received with this transaction, in the modal, as a result.
Please merge if you approve, this needs to be live asap.
=> fix(claim-modal): filter already claimed weeks

src/containers/case.js
This should be the case when there is no manual period passing button to be displayed.
Fixes #170.
=> Fix: made deadline display to take the full parent width

src/components/court-cascader-modal.js, src/components/stake-modal.js
Previously the UI suggested the user to stake the max amount of PNK available.
This led to a problem where users would be automatically unstaked from all
courts if they lost a case, because the slashing would make their PNK
balance to be lower than the amount staked.
This change introduce a suggested "buffer" of 2000 PNK to allow coping with losing
a case and not being unstaked.
It simply warns users. If they choose to ignore the warning, they can
still stake the full available balance.
=> Refactor: changed staking default value

src/components/attachment.js, src/components/case-details-card.js, src/helpers/array.js
The Court UI currently does not store the committed vote anywhere when hidden votes are enabled.
The interface can become a bit confusing, because vote and reveal would show the same options and the jurors are required to select the same options they selected in the first place. If they choose wrong, the transaction will fail (MetaMask will show a warning at least).
Since hidden votes are enabled on xDAI General Court, I implemented some changes in the voting widget that will allow to store the committed vote locally and present it to the user. To reveal, instead of selecting all options over again, it simply submits the stored vote.
~Notice that this will only work if the jurors reveal their votes using the same device they used to commit to that specific case. In case the UI cannot find …
=> Feat: store committed votes locally

package.json, src/components/case-details-card.js, yarn.lock
Latest decision was to implement missing time functionality in Reality and fix Court by fixing the ruling option parser it does use (from Reality lib).
This update re-enables the time part of DateTime disputes and replaces reality lib to have the new parser.
=> Replaces Reality Lib with the New One and Re-enables Times for Datetime Disputes

src/bootstrap/dataloader.js, src/bootstrap/web3.js, src/components/case-card.js, src/components/case-details-card.js, src/components/case-round-history.js, src/components/ongoing-cases-card.js
There is an issue with how we handle both Dynamic Scripts and Evidence Display Interfaces.
Those components usually only read things from the blockchain and IPFS, so they usually connect to the blockchain through a JSON RPC endpoint.
Currently those components are bundled and published to IPFS, which means that the JSON RPC endpoints must be calculated at bundling time and therefore are published as hardcoded values.
When it comes to Infura keys, we would never be able to deactivate/change the security restrictions of a key, risking an Evidence Display Interface or Dynamic Script stop working. Since we can only have up to 10 projects on Infura, this sounds unfeasible.
For key-less environments such as xDAI, we always risk endpoints being changed/deprecated.
This creates the following …
=> Feat: added JSON RPC endpoint and chain ID injection to scripts and display interfaces

src/bootstrap/app.js, src/bootstrap/web3.js
This was causing `drizzle` to fail unlocking MetaMask when the app was accessed for the first time and then the page would break.
To reproduce the current behavior, simply deactivate and activate the MetaMask extension and then navigate to the Court.
=> fix: remove manual window.ethereum activation

src/components/claim-modal.js
The contract that users will interact with is being wrongly instantiated from the `Web3` constructor and not the actual `web3` object. This object is provider-less, so calling `send()` does not do anything.
=> Fix: unable to claim PNK rewards

src/components/case-details-card.js
In dispute 1170, we noticed iframe is not displayed completely. Removing `iframe-resizer` seems to be fixing this issue, however, scrollbars also returned. Still better than missing info.
=> Fix Incomplete IFrame Display

src/components/claim-modal.js
`const claimStatus = contract.methods.claimStatus(account, 0, 12).call();`
The above statement was causing this bug. Initially, the juror incentive program was intended for 12 months (12 periods). So the statement is checking for 12 periods only. With March rewards, the 13th element entered the array (for Mainnet) thus the algorithm is failing to detect claimed status of March rewards and tries to claim them again and again.
Fix was simply dynamically calculating the snapshot length.
This is a high priority since it will annoy people. Please review and merge asap.
=> Fix a Bug Where Claim Modal Shows There is an Unclaimed Amount When There is Not

src/components/case-round-history.js
there seemed to be a deliberate choice
to hide the justifications for a vote
in the current ongoing round. im
not sure why.
it lies to the users (it will claim that there
are no justifications, which isn't true) and it's not obvious
why the current justifications should be hidden,
more so if the data is publicly available.
i guess rationale was to not sway jurors.
technical users can get that info from the endpoint
anyway. or they can read the network log.
=> fix: show justifications for the ongoing round

src/components/case-card.js, src/components/case-details-card.js, src/containers/case.js
Since we had two users wondering if they had bugs preventing them to vote, due to unfamiliarity with commit-reveal, it made sense to make the Reveal name explicit for the phases and show some extra info instead of just "You did not commit a vote".
Please give feedback on the messaging and feel free to contribute other explanations to clarify UX.
=> chore: show reveal phase explicitly

src/components/case-details-card.js
One user was confused about "not being able to reveal" despite being in the commit period. The previous message, "Waiting to reveal your vote", could imply that the reveal has to be done in the current period, even though the period at the top left of the screen says "Commit Period", some redundancy is probably needed for UX.
I wrote distinct messages for having made your commit and pending commit, that clarifies that the revealing has to be done in the next period
=> fix: clearer language for commit period

src/components/case-card.js, src/components/court-card.js, src/components/court-cascader-modal.js, src/components/reward-card.js
Closes #308 
added 1 more decimal
removed the '+' since it can be really confusing for the users, i think it's best if we just omit this, users should just have in mind the base reward they will ALWAYS get if they are coherent, and not take into accounts 'extras' getting their hopes up.
=> fix: coherence rewards more clear now

src/components/case-details-card.js, src/temp/arbitrable-whitelist.js
readded main tokens arbitrable to whitelist
hack to check if arbitrable is tokens address, and swaps the uri in that case for the ipfs one
verified all kleros tokens badges arbitrables are in ipfs, so they don't need handling
the ipfs uri I put into the code can be found in the replacements approved by this snapshot proposal (which wasn't executed)
https://snapshot.org/#/kleros.eth/proposal/QmSaPoLb3oKCXkmRUEQgR7ZCN1vX8dMwCUonyErBFygTtc
note both submission and removal metaevidence share this evidence display
=> fix: old kleros tokens reincluded
