src/components/court-card.js
src/components/stake-modal.js

- Move toBN inside of toWei
- Do math in BN

fix: convert staked amts to bn

---

package.json
src/bootstrap/api.js
src/components/case-details-card.js
src/components/case-round-history.js
src/components/notification-settings.js
src/temp/web3-derive-account.js
yarn.lock

- Only ask for signatures when they are necessary
- Make signature methods more informative

refactor: remove signature on page load and when submitting justifiations

---

src/components/evidence-card.js
src/components/notification-settings.js

Check existence of aliases before indexing

Hotfix: evidence with no aliases

---

src/bootstrap/dataloader.js
src/components/court-cascader-modal.js
src/components/evidence-card.js
src/components/notification-settings.js

Only fetch current fee and min stake

---

src/components/case-round-history.js

- Make ruling option buttons take whole row
- Round buttons responsive
- Justification box use word-break wrap and reset justification index on selection
closes #70 #82

fix(justifications-box): url text wrap and button responsivity

---

src/components/courts-list-card.js
src/components/evidence-card.js
src/components/stake-modal.js
src/containers/courts.js

- Expand upon set state messages. (closes #73 )
- Remove etherscan link from evidence (closes #78 )
- Fix bug in showing multiple cards for same court.

refactor(courts): show more info when setting stake

---

src/components/notification-settings.js

fix(notification-settings): allow plus in phone

---

src/containers/case.js

- Add pass period button 1hr after period should have ended (closes #94 )
- Display period timer in top bar (closes #91 and #76 )
- Add resolved tag when case is over

feat(case): add pass period btn

---

src/components/case-details-card.js

- Add section below description that links to Arbitrable Dapp if `arbitrableInterfaceURI ` is defined in MetaEvidence

feat(case-details-card): add arb dapp uri section

---

src/components/court-cascader-modal.js

feat(court-cascader): add information about PNK at stake per vote

---

netlify.toml
src/bootstrap/app.js
src/bootstrap/drizzle.js
src/components/buy-pnk-card.js
src/components/case-card.js
src/components/case-details-card.js
src/components/collapsable-card.js
src/components/court-card.js
src/components/court-cascader-modal.js
src/components/evidence-card.js
src/components/evidence-timeline.js
src/components/footer/index.js
src/components/notifications-card.js
src/components/otc-card.js
src/components/pnk-balance-card.js
src/components/pnk-exchanges-card.js
src/components/stake-modal.js
src/components/titled-list-card.js
src/components/top-banner.js
src/containers/case.js
src/containers/cases.js
src/containers/home.js

This improves UX on small devices and fixes compilation warnings.

fix:Improve UX on small devices

---

src/components/claim-modal.js

refactor(claim-modal): add second merkle tree file (march payouts for juror incentive program)

---

src/components/percentage-circle.js

- fix: fixed display text for voting performance [fixes #179]

Fix voting performance widget

---

src/components/claim-modal.js

- feat: added file for April allocation

PNK merkledrop for April

---

src/components/claim-modal.js

Please don't mind linter errors, there are 1001 errors and of course, I did not spend time to fix those.

Use a Fallback APY Calculator When Graph Query Fails

---

.babelrc
.gitignore
config-overrides.js
package.json
src/bootstrap/app.js
src/bootstrap/chain-change-watcher.js
src/bootstrap/drizzle.js
src/bootstrap/use-notifications.js
src/bootstrap/web3.js
src/components/claim-modal.js
src/components/court-cascader-modal.js
src/components/list-item.js
src/components/network-status.js
src/components/notifications-card.js
src/containers/home.js
src/hooks/use-chain-id.js
src/hooks/use-reload-on-chain-changed.js
yarn.lock

Made components update in case users switches the chain they are connected to.

Fix: on chain changed

---

src/components/claim-modal.js

Replaced Subgraph query for total staked amount, for calculating APY. The old one was not working.
Feel free to merge after approval.

fix(claim-modal): replace broken subgraph

---

src/bootstrap/api.js
src/components/case-round-history.js

The backend was broken and is fixed now. The UI code needed some love <3.

Refactor: fixed justifications on xDAI Chain

---

src/components/titled-list-card.js

Mainnet rewards reduced to 900K from 1M.

fix(titled-list-card): correct total amount distributed on Main

---

src/components/claim-modal.js
src/components/titled-list-card.js

It used to render the APY in mainnet. Now it shows APY depending on the chain, showing no APY if chain is not Mainnet or xDAI.
Thanks to @salgozino for describing the fix.
Closes #220

fix: apy shows properly in xdai

---

src/components/case-details-card.js

The solution is rather hacky and it asks the
user to reload the page. I tried a few things
but I couldn't get the component to react to the
localStorage change.
Also, this may not be the only issue with the justifications.
I haven't tested this because I don't know how to test voting, if any of you do know about this, you should try and see if you get your justification to show up. Otherwise I'd just merge and try and keep figuring out if it still doesn't work.

fix: cannot make justifications without sign key

---

src/containers/convert-pnk/convert-pnk-card.js
src/containers/convert-pnk/convert-pnk-form.js
src/containers/convert-pnk/convert-pnk.js
src/containers/convert-pnk/wihdraw-stpnk-card.js

Please @alcercu take a look on how to make it prettier
The way it works is also not ideal, it only works with integer amounts of stPNK. But I couldn't figure out how antd `InputNumber` worked with state, which is used for similar forms. If you want to take a look at it it may be the time, otherwise we could fix it whenever an user asks for it.
closes #261

Add stPNK to xPNK form in /convert-pnk

---

src/bootstrap/app.js
src/bootstrap/sentry.js
src/bootstrap/web3.js
src/components/error-boundary.js
src/components/error-fallback/index.js
src/components/error-fallback/switch-chain.js
src/containers/error-fallback.js

Implemented feature to switch to the list of supported networks when a user connects to the dapp with an unsupported network
#300

feat: Switch to supported networks on error catch

---

netlify.toml

Temporarily use alchemy endpoint to avoid being rate limited by infura.

Fix: Change mainnet fallback url

---

netlify.toml

Revert "Fix: Change mainnet fallback url"

---

src/components/case-details-card.js
src/components/evidence-card.js
src/components/evidence-timeline.js

feat: explorer links in evidence

---

src/components/court-list-item.js
src/components/courts-list-card.js
src/containers/home.js

feat: staked in courts click shows details

---

src/components/case-card.js
src/components/case-details-card.js
src/components/cases-list-card.js
src/components/ongoing-cases-card.js
src/components/performance-card.js
src/components/pnk-stats-list-card.js
src/components/reward-card.js
src/containers/case.js
src/containers/cases.js
src/hooks/use-get-draws.js
src/hooks/use-get-shifts.js

Draw and TokenAndETHShift are now obtained
from a subgraph instead, returns them faster and
hopefully more reliably.

Draw and TokenAndETHShift are now obtained from a subgraph
